apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-comment-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql-comment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: mysql-comment
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
              claimName: mysql-pv-claim-comment-ws
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: MYSQL_ROOT_PASSWORD_COMMENT_DB
          - name: MYSQL_DATABASE
            value: comment_db