apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-1
  labels:
    type: local-1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-pv1"
---    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-2
  labels:
    type: local-2
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-pv2"    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-post-ws
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-comment-ws
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi      